#!/bin/bash
#BSUB -o /home/research/jizhou.huang/projects/data-analysis-project/src/log/diabetes.%J
#BSUB -u huang.jizhou@wustl.edu
#BSUB -R 'select[type==any]'
#BSUB -q gpu-compute
#BSUB -gpu "num=1:mode=exclusive_process:gmodel=NVIDIAA10080GBSXM4"
#BSUB -a 'docker(hliucola/gracker)' /bin/true
#BSUB -N
#BSUB -W 100:00
#BSUB -J cc_diabetes
#source ...
python -m src.main --data_name diabetes --num_exp 100